baseURL = "/"
languageCode = "en-us"
title = "A Chin Web Presence"
description = "Losing the SEO game, one infrequent post at a time"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Eugene Chin"
    description = "Losing the SEO game, one infrequent post at a time"
    logo = "favicon/android-chrome-384x384.png"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:mail@eugenechin.ca"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/eugene-chin"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/chinnotchan/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/chineugene/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.flickr.com/photos/eugenechin"
    name = "flickr"
    weight = 5
